# resources/all_purpose.yml
resources:
  clusters:
    amal_eus_de:
      cluster_name: "AMAL-EUS-DE"
      spark_version: "16.4.x-scala2.12"
      azure_attributes:
        availability: "ON_DEMAND_AZURE"
      node_type_id: "Standard_DS3_v2"
      driver_node_type_id: "Standard_DS3_v2"
      autotermination_minutes: 10
      policy_id: "60643F56F1008808"
      runtime_engine: "STANDARD"
      spark_conf:
        "spark.databricks.cluster.profile": "singleNode"
      custom_tags:
        environment: "${var.env}"
        team: "AMAL"
        region: "EUS"
      autoscale:
        min_workers: 1
        max_workers: 2
