# resources/all_purpose.yml

resources:
  clusters:
    amal-eus-de-cluster:
      cluster_name: AMAL-EUS-DE-Cluster
      spark_version: 16.4.x-scala2.12
      azure_attributes:
        availability: ON_DEMAND_AZURE
      node_type_id: Standard_DS3_v2
      autotermination_minutes: 10
      policy_id: 60643F56F1008808
      runtime_engine: STANDARD
      kind: CLASSIC_PREVIEW
      is_single_node: false
      autoscale:
        min_workers: 1
        max_workers: 2
