resources:
  jobs:
    uc-migration-config-&-sync:
      name: UC_Migration_Config_&_Sync
      tasks:
      - task_key: Config_and_Sync_Batch_2
        run_if: ALL_SUCCESS
        notebook_task:
          notebook_path: /Workspace/UC Migration Framework/2. NB_Config_&_Sync
          base_parameters:
            batch: '6'
          source: WORKSPACE
        existing_cluster_id: 0130-103345-kb0sn6su
        timeout_seconds: 0
        email_notifications: {}
        webhook_notifications: {}
      - task_key: Config_and_Sync_Batch_1
        run_if: ALL_SUCCESS
        notebook_task:
          notebook_path: /Workspace/UC Migration Framework/2. NB_Config_&_Sync
          base_parameters:
            batch: '5'
          source: WORKSPACE
        existing_cluster_id: 0130-103345-kb0sn6su
        timeout_seconds: 0
        email_notifications: {}
        webhook_notifications: {}
      email_notifications:
        no_alert_for_skipped_runs: false
      timeout_seconds: 0
      max_concurrent_runs: 1
